[package]
name = "cascade-qb"
version = "0.0.1"
edition = "2021"

[dependencies]
byteorder = { workspace = true }
count-write = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, optional = true }

[features]
serde = ["dep:serde"]
