[package]
name = "cascade-cli"
version = "0.0.1"
edition = "2024"

[dependencies]
cascade-core = { workspace = true }
cascade-dump = { workspace = true, optional = true }
cascade-lut = { workspace = true, optional = true }
cascade-qb = { workspace = true }
cascade-save = { workspace = true }
cascade-thaw = { workspace = true, features = ["serde"] }
cascade-thug = { workspace = true }
cascade-thps4 = { workspace = true }
cascade-thug2 = { workspace = true, features = ["serde"] }
cascade-wad = { workspace = true, optional = true }

clap = { workspace = true }
color-eyre = { workspace = true }
encoding_rs = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
rand = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
suppaftp = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
default = []
dump = ["dep:cascade-lut", "dep:cascade-dump", "cascade-thaw/lut", "cascade-thug2/lut"]
ftp = ["dep:suppaftp"]
wad = ["dep:cascade-wad"]
