[package]
name = "cascade-app"
version = "0.3.0"
edition = { workspace = true }

[[bin]]
name = "cascade"
path = "src/main.rs"

[dependencies]
cascade-core = { workspace = true, features = ["serde"] }
cascade-qb = { workspace = true }
cascade-save = { workspace = true }
cascade-thps4 = { workspace = true }
cascade-thug2 = { workspace = true }
cascade-thaw = { workspace = true }

directories = { workspace = true }
enum-iterator = { workspace = true }
fern = { workspace = true }
image = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
rfd = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
color-eyre.workspace = true

[dependencies.iced]
version = "0.13.1"
default-features = false
features = ["tokio", "image", "debug", "wgpu"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
