[package]
name = "cascade-dump"
version = "0.0.1"
edition = "2024"

[dependencies]
cascade-lut = { workspace = true }
cascade-qb = { workspace = true }

encoding_rs = { workspace = true }
serde = { workspace = true }
