[package]
name = "cascade-thug"
version = "0.0.1"
edition = { workspace = true }

[dependencies]
cascade-core = { workspace = true }
cascade-lut = { workspace = true, optional = true }
cascade-qb = { workspace = true }
cascade-save = { workspace = true }

serde = { workspace = true, optional = true }

[dev-dependencies]
cascade-test = { workspace = true }

tokio = { workspace = true, features = ["rt", "macros"]}

[features]
serde = ["dep:serde", "cascade-qb/serde", "cascade-save/serde"]
lut = ["dep:cascade-lut"]
